Commit 12

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -36,10 +36,16 @@ jobs:
     runs-on: ubuntu-latest
     needs: build-and-push
     steps:
-      - name: Verificar estructura del repositorio
+      - name: Verificar existencia de compose.yml
         run: |
           echo "Directorio actual: $(pwd)"
-          ls -R
+          ls -R proyectoBack
+          if [ -f proyectoBack/compose.yml ]; then
+            echo "✅ Archivo compose.yml encontrado"
+          else
+            echo "❌ ERROR: Archivo compose.yml no encontrado"
+            exit 1
+          fi
 
       # 2. Transferir el archivo compose.yml al servidor remoto
       - name: Transferir el archivo compose.yml al servidor remoto
